# Generated by Django 5.0.2 on 2025-01-03 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_bio_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_tickets',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.CharField(default='default_show', max_length=255),
        ),
        migrations.AlterField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='user.show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='booked_seats',
            field=models.TextField(blank=True, default=''),
        ),
    ]
