# Generated by Django 5.0.2 on 2025-01-03 08:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_booking_event_date_remove_booking_event_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='show',
        ),
        migrations.AddField(
            model_name='booking',
            name='event_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_name',
            field=models.CharField(default='Default Event Name', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_tickets',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.show'),
        ),
        migrations.AlterField(
            model_name='show',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
    ]
